#ifndef KERNEL_INTERRUPTS_PIC_H
#define KERNEL_INTERRUPTS_PIC_H

#include <stdint.h>
#include "symbol_table.h"

#define PIC_MASTER			0x20
#define PIC_SLAVE			0xA0
#define PIC_MASTER_DATA		(PIC_MASTER + 1)
#define PIC_SLAVE_DATA		(PIC_SLAVE + 1)
#define PIC_MASTER_OFFSET	0x20
#define PIC_SLAVE_OFFSET	0x28
#define PIC_SLAVE_END		(PIC_SLAVE_OFFSET + 7)

#define PIC_ACKNOWLEDGE		0x20

#define PIC_ICW1_ICW4		0x01
#define PIC_ICW1_SINGLE		0x02
#define PIC_ICW1_INTERVAL4	0x04
#define PIC_ICW1_LEVEL		0x08
#define PIC_ICW1_INIT		0x10

#define PIC_ICW4_8086		0x01
#define PIC_ICW4_AUTO		0x02
#define PIC_ICW4_BUF_SLAVE	0x08
#define PIC_ICW4_BUF_MASTER	0x0C
#define PIC_ICW4_SFNM		0x10

#define PIC_INTERRUPT_MASK_EXCEPT_TIMER		0xFE // IRQ0
#define PIC_INTERRUPT_MASK_EXCEPT_KEYBOARD	0xFD // IRQ1
#define PIC_INTERRUPT_MASK_EXCEPT_SYSCALL	0xFB // IRQ2
#define PIC_INTERRUPT_MASK_EXCEPT_COM2		0xF7 // IRQ3
#define PIC_INTERRUPT_MASK_EXCEPT_COM1		0xEF // IRQ4
#define PIC_INTERRUPT_MASK_EXCEPT_LPT2		0xDF // IRQ5
#define PIC_INTERRUPT_MASK_EXCEPT_FLOPPY	0xBF // IRQ6
#define PIC_INTERRUPT_MASK_EXCEPT_LPT1		0x7F // IRQ7
#define PIC_INTERRUPT_MASK_NONE				0xFF
#define PIC_INTERRUPT_MASK_EXCEPT_SYSCALL_KEYBOARD_TIMER 0x70

void	pic_remap(uint8_t offset1, uint8_t offset2);
void	pic_ack(uint8_t irq);

#endif
